name: Ruby

on:
  push:
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.3.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.3.3
    - name: Install gem dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Deploy to production
      run: bundle exec cap production deploy   
